server:
  port: 8888

spring:
  application:
    name: ms-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChristianSC8/ecommerce-ms.git
          searchPaths: configs
          default-label: main
  security:
    user:
      name: ${CONFIG_USERNAME:root}
      password: ${CONFIG_PASSWORD:root}